#pragma once

namespace Brain
{

enum class PreconditionType
{
    BULLET_INTENSITY_OVER_THRESHOLD,
    LASER_INTENSITY_OVER_THRESHOLD,
    FAST_ENEMIES_OVER_THRESHOLD,
    STRONG_ENEMIES_OVER_THRESHOLD,
    OVERALL_INTENSITY_OVER_THRESHOLD,
    ENEMY_CLOSE_TO_GOAL,
    BULLET_INTENSITY_GREATER,
    LASER_INTENSITY_GREATER
};

enum class ActionType
{
    SEND_FAST_SWARM,
    SEND_STRONG_SWARM,
    HEALTH_BOOST_ALL_ENEMIES,
    SPEED_BOOST_ALL_ENEMIES,
    HEALTH_BOOST_FAST_ENEMIES,
    HEALTH_BOOST_STRONG_ENEMIES,
    SPEED_BOOST_FAST_ENEMIES,
    SPEED_BOOST_STRONG_ENEMIES,
    SMOKE_BOMB,
    NO_ACTION
};

} // namespace brain
