#pragma once

#include <vector>

/*-------------------------------------------------------
:: Author: Joe da Silva
:: Date: 18/03/2018

Struct to contain the raw pathfinding information generated by
the NavManager.

This information needs to be converted into a LevelPath
for use with the visualised game level.

---------------------------------------------------------*/
struct NavPath final
{
    NavPath()
        : success(false)
        , total_cost(0)
    {
    }

    std::vector<int> indices;
    bool success;
    int total_cost;
};
